lsps1: Use uint16 instead of uint8
BitcoinAndLightningLayerSpecs/lsp pull request #113
Opened 2024-04-19 13:15 UTC by ErikDeSmedt

The variable `funding_confirms_withing_blocks` was of type `uint8`. This  means we allowed values from 0<=x<256. This corresponds to a duration of 42 hours.

We are limiting reasonable values and should increase the range of allowed values.

Relates to https://github.com/BitcoinAndLightningLayerSpecs/lsp/issues/112
Relates to https://github.com/alexbosworth/balanceofsatoshis/issues/575

2024-04-19 13:24 UTC, SeverinAlexB approved these changes

2024-04-19 14:30 UTC, ZmnSCPxj-jr requested changes
Commit message says "use ***int8***" but actual change is "***uint16***"

Commit message should probably be "Use uint16 instead of uint8"

2024-05-02 11:28 UTC, ZmnSCPxj-jr approved these changes

2024-05-02 12:12 UTC, SeverinAlexB commented
Merge as decided in todays meeting

2024-05-02 12:12 UTC, merged